---
layout: cv
title: Riku Nakamura's CV
---
# Riku Nakamura
Computer Science

<div id="webaddress">
|<a href="https://github.com/riku05190">GitHub</a>
<!-- | <a href="https://yourusername.github.io/datascience_portfolio/gh-pages/resume.pdf">Download PDF</a> -->

| <a href="www.linkedin.com/in/riku-nakamura-49521b304">LinkedIn</a>
</div>


## Currently

Pursuing a Bachelor's degree in Computer Science at BYU-Idaho. Dedicated to creating an environment where everyone can make proactive choices through technology and community building. Currently seeking career opportunities in Japan for the 2027 graduate recruitment cycle.

### Specialized in

Java (Spring Framework), JavaScript (React Native), HTML/CSS, Marketing & Sales Strategy


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.Web Development, Data Analysis, Consumer Psychology, Self-Analysis, Community Management

## Education

Jan 2026 - Present
Brigham Young University - Idaho

B.S. in Computer Science (Expected Graduation: Spring 2027)

Apr 2024 - Dec 2025
Ensign College

Pre-transfer studies

Apr 2019 - Mar 2024
Ube National College of Technology

Associate of Engineering in Material Engineering


## Awards

`Dec 2025
Job Offer

Zensho Holdings Co., Ltd.

Jan 2026 - Present
Job Hunting Status

Currently participating in the 2027 new graduate recruitment process for LINE Yahoo (LY Corporation) and other major IT firms via ONE CAREER and ABABA.


## Publications
Aug 2025
Nakamura R, Productivity Management Application for Accounting Firms.

Developed a custom efficiency tool to streamline internal workflows and task management.

Oct 2025
Nakamura R, Matching Application for Recruitment Agencies.

Built a platform to facilitate efficient talent-company matching processes.


### Patents
Feb 2026
Freelance Service Agreement, TOKUMORI Patent/Contract 001.

Signed as a freelance developer/consultant.

## Occupation

Jul 2026 - Aug 2026 (Planned)
Internship, Japan

Mar 2024
Ube National College of Technology

Completed Associate Degree program

<!-- ### Footer

Last updated: May 2013 -->